# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='url_imagen',
            field=models.CharField(default='https://d1charzoglpx2g.cloudfront.net/media/listings/imgs/profilna.jpg', max_length=200),
        ),
    ]
