# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordstore', '0003_auto_20171111_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
